---
- name: Install necessary dependencies
  dnf:
    name: dnf-plugins-core
    state: present

- name: Install OpenJDK 17
  dnf:
    name: java-17-openjdk
    state: present

- name: Import Elastic GPG Key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic repository
  copy:
    dest: /etc/yum.repos.d/elastic.repo
    content: |
      [elastic-8.x]
      name=Elastic repository for 8.x packages
      baseurl=https://artifacts.elastic.co/packages/8.x/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled=1
      autorefresh=1
      type=rpm-md

- name: Install Logstash
  dnf:
    name: logstash
    state: present

- name: Start and enable Logstash
  service:
    name: logstash
    enabled: yes
    state: started

- name: Create mariadb.conf
  template:
    src: mysql.conf
    dest: /etc/logstash/conf.d/mysql.conf
    owner: root
    group: root
    mode: '0644'

- name: Restart MaraiDB
  service:
    name: mariadb
    state: restarted

- name: Create error.conf
  template:
    src: errors.conf
    dest: /etc/logstash/conf.d/error.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure logstash ser is in wheel group
  user:
    name: logstash
    groups: wheel
    append: yes

- name: Set permissions on MariaDB general log file
  file:
    path: /var/log/mariadb/general.log
    owner: root
    group: wheel
    mode: '0644'

- name: Set permissions on MariaDB error log file
  file:
    path: /var/log/mysql/maraidb.log
    owner: root
    group: wheel
    mode: '0644'

- name: Set permissions in MariaDB log directory
  file:
    path: /var/log/mariadb
    owner: mysql
    group: wheel
    mode: '0755'

- name: Restart Logstash
  service:
    name: logstash
    state: restarted
