---
- name: Create Prometheus user
  user:
    name: "{{ prometheus_user }}"
    system: yes
    shell: "/sbin/nologin"
    create_home: no

- name: Install UFW 
  apt:
    name: ufw
    state: present
  become: true

- name: Allow trafic for apache_exporter (9117/tcp)
  ufw:
    rule: allow
    port: "9117"
    proto: tcp
  become: true

- name: Enable UFW
  ufw:
    state: enabled
  become: true

- name: Download Apache Exporter
  get_url:
    url: "https://github.com/Lusitaniae/apache_exporter/releases/download/v{{ apache_exporter_version }}/apache_exporter-{{ apache_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/apache_exporter.tar.gz"

- name: Extract Apache exporter
  unarchive:
    src: "/tmp/apache_exporter.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes
    extra_opts: ["--strip-components=1"]

- name: Config permissions for Apache Exporter
  file:
    path: "/usr/local/bin/apache_exporter"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'

- name: Create systemd service for apache exporter
  copy:
    dest: "/etc/systemd/system/apache_exporter.service"
    content: |
      [Unit]
      Description=Prometheus Apache Exporter
      After=network.target

      [Service]
      User={{ prometheus_user }}
      ExecStart=/usr/local/bin/apache_exporter --scrape_uri=http://localhost/server-status?auto  --web.listen-address=0.0.0.0:9104
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd and enable apache exporter service
  systemd:
    daemon_reload: yes
    name: apache_exporter
    enabled: yes
    state: started
...
