---
# tasks file for mysq
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Permit trafic through 9104 for MySQL Exporter
  ufw:
    rule: allow
    port: "9104"
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
    
- name: Create prometheus user
  user:
    name: "{{ prometheus_user }}"
    system: yes
    shell: "/sbin/nologin"
    create_home: no

- name: Download MySQL Exporter
  get_url:
    url: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysql_exporter_version }}/mysqld_exporter-{{ mysql_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/mysqld_exporter.tar.gz"

- name: Extract Mysql Exporter
  unarchive:
    src: "/tmp/mysqld_exporter.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: yes
    extra_opts: ["--strip-components=1"]

- name: Set permissions for Mysql exporter
  file:
    path: "/usr/local/bin/mysqld_exporter"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'

- name: Create MySQL exporter configuration file
  copy:
    dest: "/etc/.mysqld_exporter.cnf"
    content: |
      [client]
      user=exporter
      password=yourpassword
      host=localhost
  owner: "{{ prometheus_user }}"
  group: "{{ prometheus_group }}"
  mode: '0600'

- name: Create MySQL exporter user with necessary privileges
  mysql_user:
    name: exporter
    password: ivancasillas36
    priv: "*.*:PROCESS,REPLICATION CLIENT"
    host: localhost
    state: present

- name: Create systemd service for MySQL exporter
  copy:
    dest: "/etc/systemd/system/mysqld_exporter.service"
    content: |
      [Unit]
      Description=Prometheus MySQL Exporter
      After=network.target

      [Service]
      User={{ prometheus_user }}
      ExecStart=/usr/local/bin/mysqld_exporter --config.my-cnf=/etc/.mysqld_exporter.cnf --web.listen-address=0.0.0.0:9104
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd and enable Mysql exporter service
  systemd:
    daemon_reload: yes
    name: mysqld_exporter
    enabled: yes
    state: started
...
