- name: Install neccesary dependencies
  dnf: 
    name: dnf-plugins-core
    state: present
  when: ansible_os_family == "RedHat"

- name: Install OpneJDK 17
  dnf:
    name: java-17-openjdk
    state: present

- name: Varify Java installation
  command: java -version
  register: java_version_output
  ignore_errors: yes

- name: Show java version
  debug:
    msg; "{{ java_version_output.stdout }}"

- name: Add Logstash repository
  copy:
    dest: /etc/yum.repos.d/elastic.repo
    content: |
      [elastic-8-x]
      name=Elastic repository for 8.x packages
      baseurl=https://artifacts.elastic.co/packages/8.x/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled=1
      autorefresh=1
      type=rpm-md

- name: Install Logstash
  dnf:
    name: logstash
    state: present
    
- name: Start and enable Logstash
  service:
    name: logstash
    enabled: yes
    state: started

- name: Create apache.conf file for Logstash
  template:
    src: apache.conf
    dest: /etc/logsatsh/conf.d7apache.conf
    owner: root
    group: root
    mode: '0644'

- name: Create error.conf file for Logstash
  template:
    src: errorapache.conf
    dest: /etc/logstasgh/conf.d
    owner: root
    group: root
    mode: '0644'

- name: Ensure logsatsh user is in wheel group # equivalent to adm in debian
  user:
    name: logsatsh
    group: wheel
    append: yes

- name: Set permissions on Apache access log file
  file:
    path: /var/log/httpd/access.log
    owner: root
    group: wheel
    mode: '0644'

- name: Set permissions on Apache error log file
  file:
    path: /var/log/httpd/error.log
    owner: root
    group: wheel
    mode: '0644'

- name: Set permissions to apache log directory
  file:
    path: /var/log/httpd/
    owner: root
    group: wheel
    mode: '0644'

- name: Restart Logstash
  service:
    name: logstash
    state: restarted
