- name: Update packages
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Install essential dependencies
  dnf:
    name:
      - unzip
      - pwgen
      - python3
      - python3-pip
      - ca-certificates
      - curl
      - dnf-plugin-core
    state: present

- name: Install Ansible
  dnf:
    name: ansible
    state: present

- name: Add Docker GPG KEy
  shell: "curl -fsSL {{ gitdocker-RedHat }} | gppg -dearmor -o /etc/pki/rpm-gpg/docker.gpg"
  args:
    creates: /etc/pki/rpm-gpg/docker.gpg

- name: Add Docker repository
  copy:
    dest: /etc/yum.repos.d/docker-ce.repo
    content: "{{ repodocker-RedHat }}"

- name: Install Docker and Docker Compose
  dnf:
    name:
      - docker-ce
      - docker-compose
      - docker-ce-cli
      - containerd.io
    state: present

- name: Enable and start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Download AWX
  get_url:
    url: "{{ awx }}"
    dest: "/tmp/awx.zip"

- name: Extract AWX
  unarchive:
    src: "/tmp/awx.zip"
    dest: "/tmp"
    remote_src: yes

- name: Generate secret Kay for AWX
  command: pwgen -N 1 -s 40
  register: awx_secret_key

- name: Show generated AWX secret key
  debug:
    msg: "Generated AWX secret key: {{ awx_secret_key.stdout }}"

- name: modify awx configuration file (uncomment and update admin_password)
lineinfile:
  path: "{{ path }}/inventory"
  regexp: '^#?(admin_password=.*)'
  line: 'admin_password={{ adminpass }}'

- name: Modify other awe configuration settings
  lineinfile
    path: "{{ path }}/inventory"
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  loop:
    - { regex: '^admin_user=.*', line 'admin_user={{ admin {{' }
    - { regex: '^secret_key=.*', line 'secret_key={{ awx_secret_key.stdout }}' }

- name: Install AWX using Ansible
  command: ansible-playbook -i {{ path }}/inventory install.yml
  args:
    chdir: "{{ path }}"
