---
- name: Update all system packages
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Install essential dependencies
  dnf:
    name:
      - unzip
      - pwgen
      - python3
      - python3-pip
      - ca-certificates
      - curl
      - dnf-plugins-core
    state: present

- name: Install Ansible
  dnf:
    name: ansible
    state: present

- name: Upgrade pip
  pip:
    name: pip
    state: latest
    executable: pip3

- name: Install compatible versions of Docker SDK and dependencies
  pip:
    name:
      - docker==6.1.3
      - requests==2.31.0
    state: present
    executable: pip3

- name: Add Docker GPG Key
  shell: "curl -fsSL {{ gitdocker_redhat }} -o /etc/pki/rpm-gpg/docker.gpg"
  args:
    creates: /etc/pki/rpm-gpg/docker.gpg

- name: Add Docker repository
  copy:
    dest: /etc/yum.repos.d/docker-ce.repo
    content: "{{ repodocker_redhat }}"

- name: Install Docker Engine and CLI
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Install Docker Compose V2 plugin
  dnf:
    name: docker-compose-plugin
    state: present

- name: Create docker-compose symlink for compatibility
  file:
    src: /usr/libexec/docker/cli-plugins/docker-compose
    dest: /usr/local/bin/docker-compose
    state: link
    force: yes

- name: Enable and start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Check if Docker Compose V2 is available
  command: docker compose version
  register: docker_compose_v2
  ignore_errors: yes
  environment:
    DOCKER_HOST: unix:///var/run/docker.sock

- name: Fail if Docker Compose V2 is not installed
  fail:
    msg: "Docker Compose V2 is required but not found. Please install Docker Compose V2."
  when: docker_compose_v2.rc is defined and docker_compose_v2.rc != 0

- name: Install Docker-Compose
  pip:
    name: docker-compose
    state: present
    executable: pip3

- name: Download AWX
  get_url:
    url: "{{ awx }}"
    dest: "/tmp/awx.zip"

- name: Extract AWX archive
  unarchive:
    src: "/tmp/awx.zip"
    dest: "/tmp"
    remote_src: yes

- name: Generate secret key for AWX
  command: pwgen -N 1 -s 40
  register: awx_secret_key

- name: Show generated AWX secret key
  debug:
    msg: "Generated AWX secret key: {{ awx_secret_key.stdout }}"

- name: Set admin_password in AWX inventory
  lineinfile:
    path: "{{ path }}/inventory"
    regexp: '^#?(admin_password=.*)'
    line: "admin_password={{ adminpass }}"

- name: Update other AWX inventory settings
  lineinfile:
    path: "{{ path }}/inventory"
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  loop:
    - { regex: '^admin_user=.*', line: "admin_user={{ admin }}" }
    - { regex: '^secret_key=.*', line: "secret_key={{ awx_secret_key.stdout }}" }

- name: Run AWX installer playbook
  command: ansible-playbook -i {{ path }}/inventory install.yml
  args:
    chdir: "{{ path }}"
  environment:
    PATH: "/usr/local/bin:/usr/bin:/bin"
    DOCKER_HOST: unix:///var/run/docker.sock
