---
- name: Intall necessary dependences for Elasticsearch
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present
    update_cache: yes

- name: Add GPG Key for Elasticsearch
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main"
    state: present
    filename: elasticsearch

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

 Set kibana configuration file
- name: Set elasticsearch config file
  template:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: '0664'

- name: Enable ant start Elasticsearch
  service:
    name: elasticsearch
    enabled: yes
    state: started
...
