---
- name: Install neccessary dependences
  apt:
    name:
      - curl
      - wget
      - ca-certificates
      - gnupg
      - software-properties-common
      - libnss3
      - libnspr4
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libxcomposite1
      - libxdamage1
      - libxfixes3
      - libxrandr2
      - libgbm1
      - libxkbcommon0
      - libasound2
    state: present
    update_cache: yes

- name: Install Node.js
  shell: curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs

- name: Create Playwright directory
  file:
    path: /opt/playwright-test
    state: directory
    mode: '0755'

- name: Init Node.js project
  shell: npm init -y
  args:
    chdir: /opt/playwright-test/
    creates: /opt/playwright-test/package.json

- name: Install playwright
  shell: npm install -D playwright
  args:
    chdir: /opt/playwright-test

- name: Install Playwright browsers
  shell: npx playwright install
  args:
    chdir: /opt/playwright-test

- name: Create test scripy for Playwright
  copy:
    dest: /opt/playwright-test/test_apache.js
    content: |
      const { chromium } = require('playwright');
      const fs = require('fs');

      (async () => {
        const browser = await chromium.launch();
        const page = await browser.newPage();

        const start = Date.now();
        try {
          await page.goto('http://172.26.203.191');
          await page.waitForTimeout(1000);
          console.log('Acceso exitoso');
        } catch (error) {
          console.error('Error en el acceso:', error);
        }
        const duration = Date.now() - start;
        console.log(`Tiempo de carga: ${duration} ms`);
        fs.appendFileSync('metrics.log', `access_duration_ms ${duration}\n`);
        await browser.close();
      })();
