---
- name: Node-exporter installation
  hosts: mariadb
  become: yes
  become_method: sudo
  roles:
    - roles

- name: Node-exporter installation
  hosts: wordpress
  become: yes
  become_method: sudo
  roles:
    - roles
...
