---
# task file for grafana installation in Debian
#-----------------------Instalación Grafana Debian-----------------------
- name: Add Grafana GPG key
  apt_key:
    url: "{{ grafana_debian_key }}"
    state: present

- name: Add Grafana APT repository
  apt_repository:
    repo: "{{ grafana_debian_repo }}"
    state: present
    filename: grafana
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Enable and start grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: Ensure Grafana service restarted
  service:
    name: grafana-server
    state: restarted
...
